# Generated by Django 5.0 on 2024-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='isBankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
